name: Compilar APK de Fichas Clínicas

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ControldevisitasAPP

    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4

      - name: Configurar Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Verificar Entorno Flutter
        run: flutter doctor -v

      - name: Instalar Dependencias
        run: flutter pub get

      - name: Construir APK (Release)
        run: flutter build apk --release

      - name: Subir APK como Artifact (Descargable)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: ControldevisitasAPP/build/app/outputs/flutter-apk/app-release.apk
